### PR TITLE
Report types can now be selected for rule. Fixes #54

### LINKED ISSUE #54: Feature request: choose report types for Coverage
Right now two kind of reports are generated: for class and for each method.
I would be nice to have an option to choose which reports are required (both, only one, none). For example, my team only cares about class coverage reports.

### PR DESCRIPTION
**Pull request by ov7a**

### CODE REVIEW

**Comment by vch-lm** [comment]
@falko could you also look at this PR, please? I'm unsure if I need to write a test on it, because the changes are very simple and I've tested in manually.

**Comment by ov7a** [comment]
@falko could you also look at this PR, please? I'm unsure if I need to write a test on it, because the changes are very simple and I've tested in manually.

**Comment by ov7a** [comment]
@falko, thank you! Done!

**Comment by ov7a** [comment]
@falko I'd also would like to ask: are there any plans for release? I've seen that the latest release was in 2017, can I hope that my PR will be released?

**Comment by falko** [comment]
I might push a release out to get Spring Boot support for 7.13 done. But no timeline yet. It depends on the progress with the archetypes.

**Pull request merged**
